### PR TITLE
Fix Sensor daemonset pod annotations

### PR DESCRIPTION
**Pull request by lir-wiz**
Fixed indentation issues

### CODE REVIEW

**Comment by lir-wiz** [comment]
@ariknem I'm not sure how to bump the chart version

**Comment by ariknem** [comment]
please don't merge this through github!

**Comment by ariknem** [comment]
will publish from internal location

**Comment by ariknem** [comment]
@lir-wiz this is now resolved (the new chart is published). the unified chart version 0.1.52 contains the fix

**Pull request closed without merging**
